import type { Perfume } from './perfumes';

export const perfumes: Perfume[] = [
  {
    id: 1,
    name: '탬버린즈 블루 히노키',
    brand: 'Tamburins',
    description: 'An alluring and mysterious fragrance that combines spicy notes with deep woods.',
    imageUrl: 'https://web-resource.tamburins.com/catalog/product/12001607/24ff9966-538d-457d-b9a4-da25e427d9b9/thumbnail_11ml_Perfume_Hinoki.jpg',
    purchaseUrl: '#',
    notes: ['Black Pepper', 'Incense', 'Sandalwood', 'Oud'],
  },
  {
    id: 2,
    name: '브랜드명 모델명',
    brand: '브랜드명',
    description: 'A light and airy floral scent, perfect for daytime wear and spring afternoons.',
    imageUrl: 'https://placehold.co/400x500.png',
    purchaseUrl: '#',
    notes: ['Peony', 'Jasmine', 'White Musk', 'Bergamot'],
  },
  {
    id: 3,
    name: '브랜드명 모델명',
    brand: '브랜드명',
    description: 'A warm and inviting perfume with rich amber and a hint of sweet vanilla.',
    imageUrl: 'https://placehold.co/400x500.png',
    purchaseUrl: '#',
    notes: ['Amber', 'Vanilla Bean', 'Tonka', 'Tobacco'],
  },
  {
    id: 4,
    name: '브랜드명 모델명',
    brand: '브랜드명',
    description: 'A vibrant and energetic citrus explosion, capturing the essence of a sun-drenched grove.',
    imageUrl: 'https://placehold.co/400x500.png',
    purchaseUrl: '#',
    notes: ['Grapefruit', 'Lemon Verbena', 'Neroli', 'Vetiver'],
  },
    {
    id: 5,
    name: 'Oceanic Mist',
    brand: 'Aqua Aromas',
    description: 'A fresh and clean aquatic scent that evokes the feeling of a cool sea breeze.',
    imageUrl: 'https://placehold.co/400x500.png',
    purchaseUrl: '#',
    notes: ['Sea Salt', 'Sage', 'Ambrette', 'Driftwood'],
  },
  {
    id: 6,
    name: 'Velvet Rose',
    brand: 'Fleur Fragrances',
    description: 'A modern take on a classic rose, blending Bulgarian rose with a hint of spicy saffron.',
    imageUrl: 'https://placehold.co/400x500.png',
    purchaseUrl: '#',
    notes: ['Rose', 'Saffron', 'Patchouli', 'Musk'],
  },
  {
    id: 7,
    name: 'Midnight Jasmine',
    brand: 'Artisan Scents',
    description: 'An intoxicating and romantic jasmine scent, perfect for evening occasions.',
    imageUrl: 'https://placehold.co/400x500.png',
    purchaseUrl: '#',
    notes: ['Jasmine Sambac', 'Ylang-Ylang', 'Gardenia', 'Sandalwood'],
  },
  {
    id: 8,
    name: 'Spiced Orchard',
    brand: 'Maison de Luxe',
    description: 'A cozy and comforting fragrance with notes of apple, cinnamon, and warm woods.',
    imageUrl: 'https://placehold.co/400x500.png',
    purchaseUrl: '#',
    notes: ['Apple', 'Cinnamon', 'Cedarwood', 'Cardamom'],
  },
];